#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
#    password: 1234
#    username: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
server:
  port: 9988




db:
  driver: com.mysql.jdbc.Driver
  password: 1234
  url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
  username: root
entitymanager:
  packagesToScan: org
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl:
    auto: create
  show_sql: true
#spring:
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true


